version: "3.3"

services:
  jenkins:
    user: root
    image: "96af22c8cdbf"
    ports:
      - "8085:3005"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge
